// Generated by WebFx

module webfx.demo.enzoclocks.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.type;
    requires webfx.extras.visual;
    requires webfx.extras.visual.controls.grid;
    requires webfx.kit.util;
    requires webfx.lib.enzo;
    requires webfx.platform.client.uischeduler;

    // Exported packages
    exports webfx.demo.enzoclocks;
    exports webfx.demo.enzoclocks.circlespacker;
    exports webfx.demo.enzoclocks.settings;

    // Provided services
    provides javafx.application.Application with webfx.demo.enzoclocks.EnzoClocksApplication;

}